name: Release

on:
  release:
    types: [created]

env:
  APP_NAME: permissions_overwrite

jobs:
  release:
    name: Build release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup krankler
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.5_amd64.deb
          sudo apt install ./libssl1.0.0_1.0.2n-1ubuntu5.5_amd64.deb
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.12.3/krankerl
          chmod +x krankerl
      - name: Package app
        run: ./krankerl package
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}.tar.gz
          asset_name: ${{ env.APP_NAME }}.tar.gz
          tag: ${{ github.ref }}
